#include "scrcpy_ffi_internal.h"

// Pause is a local privacy/resource boundary: no event generated by Flutter
// may reach Android while the session is visually paused. Keep this check in
// the native boundary as well as Dart so callers cannot bypass it by invoking
// the exported FFI symbols directly.
static bool
ffi_scrcpy_controls_enabled(const ScrcpyFfiInstance *s) {
    return s
        && atomic_load_explicit(&s->running, memory_order_acquire)
        && s->controller_started
        && !atomic_load_explicit(&s->decode_paused, memory_order_acquire);
}

/**
 * @brief Sends a multitouch event down to the target Android device.
 * Coordinates are mapped dynamically to the current tracked frame resolution.
 */
FFI_EXPORT void ffi_scrcpy_send_touch(void*    handle,
                                      uint8_t  action,
                                      uint64_t pointer_id,
                                      float    x, float y,
                                      float    pressure) {
    ScrcpyFfiInstance* s = (ScrcpyFfiInstance*)handle;
    if (!ffi_scrcpy_controls_enabled(s)) return;

    struct sc_control_msg msg = { .type = SC_CONTROL_MSG_TYPE_INJECT_TOUCH_EVENT };
    msg.inject_touch_event.action     = (enum android_motionevent_action)action;
    msg.inject_touch_event.pointer_id = pointer_id;
    msg.inject_touch_event.position.point.x =
        (uint32_t)(x * (float)s->frame_width);
    msg.inject_touch_event.position.point.y =
        (uint32_t)(y * (float)s->frame_height);
    msg.inject_touch_event.position.screen_size.width =
        (uint16_t)s->frame_width;
    msg.inject_touch_event.position.screen_size.height =
        (uint16_t)s->frame_height;
    msg.inject_touch_event.pressure     = pressure;
    msg.inject_touch_event.action_button = 0;
    msg.inject_touch_event.buttons = (action == 0 || action == 2) ? 1 : 0;
    sc_controller_push_msg(&s->controller, &msg);
}

/**
 * @brief Sends a keyboard stroke down to the target Android device.
 */
FFI_EXPORT void ffi_scrcpy_send_key(void* handle, uint32_t keycode, uint8_t action,
                                    uint32_t repeat, uint32_t metastate) {
    ScrcpyFfiInstance* s = (ScrcpyFfiInstance*)handle;
    if (!ffi_scrcpy_controls_enabled(s)) return;

    struct sc_control_msg msg = { .type = SC_CONTROL_MSG_TYPE_INJECT_KEYCODE };
    msg.inject_keycode.action    = (enum android_keyevent_action)action;
    msg.inject_keycode.keycode   = (enum android_keycode)keycode;
    msg.inject_keycode.repeat    = repeat;
    msg.inject_keycode.metastate = (enum android_metastate)metastate;
    sc_controller_push_msg(&s->controller, &msg);
}

/**
 * @brief Sends a trackpad/mouse scroll event down to the target Android device.
 */
FFI_EXPORT void ffi_scrcpy_send_scroll(void* handle, float x, float y,
                                       float h_scroll, float v_scroll) {
    ScrcpyFfiInstance* s = (ScrcpyFfiInstance*)handle;
    if (!ffi_scrcpy_controls_enabled(s)) return;

    struct sc_control_msg msg = { .type = SC_CONTROL_MSG_TYPE_INJECT_SCROLL_EVENT };
    msg.inject_scroll_event.position.point.x =
        (uint32_t)(x * (float)s->frame_width);
    msg.inject_scroll_event.position.point.y =
        (uint32_t)(y * (float)s->frame_height);
    msg.inject_scroll_event.position.screen_size.width =
        (uint16_t)s->frame_width;
    msg.inject_scroll_event.position.screen_size.height =
        (uint16_t)s->frame_height;
    msg.inject_scroll_event.hscroll = h_scroll;
    msg.inject_scroll_event.vscroll = v_scroll;
    sc_controller_push_msg(&s->controller, &msg);
}

/**
 * @brief Sends a BACK key code press or triggers screen-on command.
 */
FFI_EXPORT void ffi_scrcpy_send_back_or_screen_on(void* handle) {
    ScrcpyFfiInstance* s = (ScrcpyFfiInstance*)handle;
    if (!ffi_scrcpy_controls_enabled(s)) return;
    struct sc_control_msg msg = { .type = SC_CONTROL_MSG_TYPE_BACK_OR_SCREEN_ON };
    msg.back_or_screen_on.action = AKEY_EVENT_ACTION_DOWN;
    sc_controller_push_msg(&s->controller, &msg);
}

/**
 * @brief Direct text string injection for text input areas.
 */
FFI_EXPORT void ffi_scrcpy_inject_text(void* handle, const char* text) {
    ScrcpyFfiInstance* s = (ScrcpyFfiInstance*)handle;
    if (!ffi_scrcpy_controls_enabled(s) || !text) return;
    struct sc_control_msg msg = { .type = SC_CONTROL_MSG_TYPE_INJECT_TEXT };
    msg.inject_text.text = strdup(text);
    sc_controller_push_msg(&s->controller, &msg);
}

/**
 * @brief Synchronizes the local clipboard down to the Android target device.
 */
FFI_EXPORT void ffi_scrcpy_set_clipboard(void* handle, const char* text, bool paste) {
    ScrcpyFfiInstance* s = (ScrcpyFfiInstance*)handle;
    if (!ffi_scrcpy_controls_enabled(s) || !text) return;
    struct sc_control_msg msg = { .type = SC_CONTROL_MSG_TYPE_SET_CLIPBOARD };
    msg.set_clipboard.text  = strdup(text);
    msg.set_clipboard.paste = paste;
    sc_controller_push_msg(&s->controller, &msg);
}

/**
 * @brief SDL Thread utility helper function to verify if executing on the main GUI thread.
 */
bool sc_SDL_IsMainThread(void) {
    return true; 
}

/**
 * @brief SDL override hook. Intercepts clipboard changes on the device and triggers Dart side notifications.
 */
int sc_SDL_SetClipboardText(const char *text) {
    char *copy = strdup(text ? text : "");
    ScrcpyFfiInstance* s = (ScrcpyFfiInstance*)t_instance_handle;
    if (s && s->clipboard_cb) {
        s->clipboard_cb(s, copy);
    } else {
        free(copy);
    }
    return 0;
}

/**
 * @brief SDL override hook for retrieving host clipboard text. Unused since updates are pushed.
 */
char *sc_SDL_GetClipboardText(void) {
    return strdup("");
}

/**
 * @brief Safe frame copier. Converts the current frame's internal FFmpeg planar format
 * and interleaves U/V layers directly into the host's target NV12 buffer layout.
 */
FFI_EXPORT bool ffi_scrcpy_copy_to_nv12(
    void* handle,
    int32_t* out_width,
    int32_t* out_height,
    uint8_t* dst_y,
    int32_t dst_y_stride,
    uint8_t* dst_uv,
    int32_t dst_uv_stride
) {
    ScrcpyFfiInstance* s = (ScrcpyFfiInstance*)handle;
    if (!s) return false;

    sc_mutex_lock(&s->buffer_mutex);
    if (!s->current_frame) {
        sc_mutex_unlock(&s->buffer_mutex);
        return false;
    }
    
    int width = s->current_frame->width;
    int height = s->current_frame->height;
    
    if (out_width)  *out_width  = width;
    if (out_height) *out_height = height;
    
    if (!dst_y || !dst_uv) {
        sc_mutex_unlock(&s->buffer_mutex);
        return true; 
    }

    // Hardware frames expose an opaque native surface, not CPU-addressable
    // Y/U/V planes. Never map them back to CPU just to satisfy a legacy API.
    if (s->current_frame->hw_frames_ctx) {
        sc_mutex_unlock(&s->buffer_mutex);
        return false;
    }
    
    const uint8_t* src_y = s->current_frame->data[0];
    const uint8_t* src_u = s->current_frame->data[1];
    const uint8_t* src_v = s->current_frame->data[2];
    
    int src_y_stride = s->current_frame->linesize[0];
    int src_u_stride = s->current_frame->linesize[1];
    int src_v_stride = s->current_frame->linesize[2];
    
    int copy_y_width = width < dst_y_stride ? width : dst_y_stride;
    for (int y = 0; y < height; y++) {
        memcpy(dst_y + y * dst_y_stride, src_y + y * src_y_stride, copy_y_width);
    }
    
    int half_width = width / 2;
    int half_height = height / 2;
    int copy_uv_width = half_width * 2 < dst_uv_stride ? half_width : (dst_uv_stride / 2);
    for (int y = 0; y < half_height; y++) {
        const uint8_t* row_u = src_u + y * src_u_stride;
        const uint8_t* row_v = src_v + y * src_v_stride;
        uint8_t* row_dst = dst_uv + y * dst_uv_stride;
        
        for (int x = 0; x < copy_uv_width; x++) {
            row_dst[x * 2]     = row_u[x];
            row_dst[x * 2 + 1] = row_v[x];
        }
    }
    
    sc_mutex_unlock(&s->buffer_mutex);
    return true;
}
